### ISSUE TITLE
Exception: yfinance failed to decrypt Yahoo data response

### ISSUE THREAD

**Issue by Shivashish-Roy** [skrishnan2001/Stock-Price-Predictor#2] opened 2023-02-21 14:27 UTC
for yfinance 0.2.12

**Comment by skrishnan2001** [comment] 2023-04-01 13:20
As of now till the decryption issue is fixed in yfinance, we can migrate the code to yahooquery library. Will revert when the issue is fixed in yfinance.

**Closed as completed by skrishnan2001** 2023-04-01 13:20 UTC
